#!/usr/bin/env python3
"""
validate_against_prism.py

Cross-validates NETVA's AMC solver (backend/amc) against PRISM, an
independent probabilistic model checker.

What it does, in order:
  1. Runs NETVA's real pipeline (ingestion -> normalization -> attack graph
     -> AMC) to get the live Q/R matrices and NETVA's own computed
     absorption probabilities (B) and expected steps (t_vec).
  2. Generates a PRISM .pm model + .pctl properties file from those SAME
     matrices (so PRISM is solving the exact same problem NETVA solved).
  3. Shells out to the `prism` binary to solve it independently.
  4. Parses PRISM's results, lines them up against NETVA's own numbers,
     prints a comparison table, and gives an overall PASS/FAIL.

Requirements:
  - PRISM installed and the `prism` command on your PATH.
    Download: https://www.prismmodelchecker.org  (Java-based, desktop tool,
    not a hosted API -- you install it locally / in CI).
  - Run this from a location where NETVA's `backend` package is importable
    (e.g. from the NETVA/ project root), OR set NETVA_ROOT below.

Usage:
    python3 validate_against_prism.py
    python3 validate_against_prism.py --tolerance 0.001
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

# ── Locate NETVA's backend package ──────────────────────────────────────────
# If this script doesn't live at NETVA/validation/prism/, point this at your
# NETVA project root (the folder containing `backend/`).
NETVA_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(NETVA_ROOT))

OUT_DIR = Path(__file__).resolve().parent
PM_FILE = OUT_DIR / "netva_amc.pm"
PCTL_FILE = OUT_DIR / "netva_amc.pctl"
PRISM_LOG = OUT_DIR / "prism_raw_output.txt"


# ── Step 1: run NETVA's real pipeline ───────────────────────────────────────
def run_netva_amc():
    import os
    os.environ.setdefault("NETVA_SIMULATE", "1")

    from backend.ingestion import ingest_all
    from backend.normalization import Normalizer, Deduplicator
    from backend.graph import build_attack_graph
    from backend.amc import run_amc

    raw = ingest_all(use_lab_defaults=True)
    network = Normalizer().normalize(**{k: raw[k] for k in raw})
    network = Deduplicator().deduplicate(network)
    G, paths = build_attack_graph(network)
    amc = run_amc(G, network)
    return amc


# ── Step 1.5: sanity-check NETVA's own numbers, independently ──────────────
def self_check_netva(amc):
    """Before blaming PRISM or the translation step, re-solve NETVA's own
    Q/R with a completely separate numpy routine and see if amc.B / amc.t_vec
    are even internally consistent with the Q/R matrices NETVA itself
    produced. Catches NETVA-side solver/display bugs vs. translation bugs."""
    import numpy as np
    t = amc.Q.shape[0]
    N_check = np.linalg.inv(np.eye(t) - amc.Q)
    B_check = N_check @ amc.R
    t_check = N_check @ np.ones(t)

    diff_B = float(np.max(np.abs(amc.B - B_check)))
    diff_t = float(np.max(np.abs(amc.t_vec - t_check)))
    print(f"      Self-check (independent inversion of NETVA's own Q/R):")
    print(f"        max |amc.B - fresh (I-Q)^-1 R|   = {diff_B:.2e}")
    print(f"        max |amc.t_vec - fresh N @ 1|    = {diff_t:.2e}")
    if diff_B > 1e-6 or diff_t > 1e-6:
        print("        [WARN] amc.B/t_vec are NOT internally consistent with")
        print("        amc.Q/amc.R -- this points to a bug in NETVA's own")
        print("        solver or in how results get attached, independent of")
        print("        PRISM entirely. Worth investigating backend/amc/solver.py.")
    return B_check, t_check


# ── Step 2: generate PRISM model + properties from NETVA's own matrices ────
def write_prism_files(amc) -> tuple[list[str], list[str]]:
    import numpy as np
    ts = amc.transient_states
    abss = amc.absorbing_states
    Q = amc.Q
    R = amc.R
    t, a = len(ts), len(abss)

    def safe(label: str) -> str:
        """PRISM label/identifier names must match [A-Za-z_][A-Za-z0-9_]*
        -- i.e. they cannot start with a digit, even inside quotes. NETVA's
        state IDs are often IPs ("10.20.0.20::root"), which would otherwise
        produce an illegal label starting with '1'. Prefix with 's_' to
        guarantee a legal identifier."""
        cleaned = re.sub(r"[^0-9A-Za-z_]", "_", label)
        return "s_" + cleaned

    lines = [
        "dtmc",
        "",
        "// Auto-generated by validate_against_prism.py from live NETVA AMC output",
        "// DO NOT hand-edit -- regenerate by re-running the script.",
        "",
        "module netva_amc",
        f"    s : [0..{t + a - 1}];",
        "",
    ]

    translation_warnings = []

    for i in range(t):
        real_terms = []
        for k in range(t):
            p = Q[i, k]
            if p > 1e-9:
                real_terms.append((k, p))
        for k in range(a):
            p = R[i, k]
            if p > 1e-9:
                real_terms.append((t + k, p))
        used = sum(p for _, p in real_terms)
        self_loop = 1.0 - used

        terms = list(real_terms)
        if self_loop > 1e-9:
            # NOTE: if the graph already has a genuine self-referencing edge
            # (Q[i,i] != 0), this appends a SECOND (i, ...) tuple alongside
            # it. That's fine -- PRISM sums multiple outcomes targeting the
            # same successor within one distribution, so the emitted .pm
            # semantics are still correct (confirmed: PRISM's own results
            # matched NETVA's B/t_vec exactly). It just means we must NOT
            # use "dst == i" as a proxy for "this is the synthetic self-loop"
            # when fidelity-checking below.
            terms.append((i, self_loop))

        rounded = [(dst, round(p, 6)) for dst, p in terms]
        diff = round(1.0 - sum(p for _, p in rounded), 6)
        if abs(diff) > 0:
            idx_max = max(range(len(rounded)), key=lambda x: rounded[x][1])
            dst, p = rounded[idx_max]
            rounded[idx_max] = (dst, round(p + diff, 6))

        # Translation fidelity check: compare only the REAL terms (i.e.
        # exactly what Q[i]/R[i] contain) against Q[i]/R[i] themselves --
        # deliberately built from `real_terms`, not `rounded`/`terms`, so the
        # synthetic self-loop reservation never enters this comparison
        # regardless of whether dst happens to equal i.
        encoded_q = np.zeros(t)
        encoded_r = np.zeros(a)
        for dst, p in real_terms:
            if dst < t:
                encoded_q[dst] += round(p, 6)
            else:
                encoded_r[dst - t] += round(p, 6)
        row_diff_q = np.max(np.abs(encoded_q - Q[i])) if t else 0.0
        row_diff_r = np.max(np.abs(encoded_r - R[i])) if a else 0.0
        if row_diff_q > 1e-5 or row_diff_r > 1e-5:
            translation_warnings.append(
                f"    [WARN] state {i} ({ts[i]}): encoded row deviates from "
                f"amc.Q/amc.R by up to {max(row_diff_q, row_diff_r):.2e}"
            )

        rhs = " + ".join(f"{p:.6f} : (s'={dst})" for dst, p in rounded)
        lines.append(f"    [] s={i} -> {rhs};")

    if translation_warnings:
        print("      [!] .pm translation fidelity check found mismatches:")
        for w in translation_warnings:
            print(w)
    else:
        print("      Translation fidelity check: every row matches amc.Q/amc.R exactly.")

    for j in range(a):
        lines.append(f"    [] s={t + j} -> 1.0 : (s'={t + j});")

    lines += ["endmodule", ""]
    for j, name in enumerate(abss):
        lines.append(f'label "{safe(name)}" = s={t + j};')
    # A single label covering ALL absorbing states -- used for the *correct*
    # "expected steps to absorption" query. R{"steps"}=?[F "<one target>"] is
    # only finite when that target is reached with probability 1, which is
    # rarely true when there are multiple absorbing states -- it'll come back
    # Infinity for almost every state. NETVA's own t_vec is "expected steps
    # until absorption into ANY target", so that's what we must ask PRISM too.
    lines.append(f'label "any_absorbing" = s>={t};')
    lines += ["", 'rewards "steps"']
    for i in range(t):
        lines.append(f"    s={i} : 1;")
    lines += ["endrewards", ""]

    # NETVA's B[i,j] / t_vec[i] treat EVERY transient state as its own
    # hypothetical starting point (a per-row fundamental-matrix computation
    # -- well-defined even for states with no predecessors in the graph).
    # PRISM instead builds a model with a SINGLE initial state by default and
    # only analyses states reachable from it, silently dropping any state
    # with no incoming path (they simply won't appear in filter(print,...)
    # output at all -- NOT the same as their value being zero). Declaring
    # every state as a valid initial state via `init true endinit` makes
    # PRISM's reachable set the full state space too, matching NETVA's
    # per-state semantics.
    lines += ["init", "    true", "endinit", ""]

    PM_FILE.write_text("\n".join(lines))

    # Per-target absorption PROBABILITY (well-defined, matches columns of B) +
    # one global expected-STEPS-to-any-absorption property (matches t_vec).
    props = []
    for name in abss:
        lab = safe(name)
        props.append(f'filter(print, P=? [ F "{lab}" ])')
    props.append('filter(print, R{"steps"}=? [ F "any_absorbing" ])')
    PCTL_FILE.write_text("\n".join(props) + "\n")

    return ts, abss


# ── Step 3: run PRISM ───────────────────────────────────────────────────────
def run_prism() -> str:
    if shutil.which("prism") is None:
        print(
            "\n[ERROR] `prism` executable not found on PATH.\n"
            "Install it from https://www.prismmodelchecker.org (unzip, then add\n"
            "its bin/ folder to PATH), or set PATH before re-running this script.\n"
        )
        sys.exit(1)

    result = subprocess.run(
        ["prism", str(PM_FILE), str(PCTL_FILE)],
        capture_output=True, text=True, timeout=300,
    )
    output = result.stdout + "\n" + result.stderr
    PRISM_LOG.write_text(output)
    return output


# ── Step 4: parse PRISM output ──────────────────────────────────────────────
def parse_prism_filter_output(raw: str, num_props: int, num_states: int) -> list[list[float]]:
    """
    Parses `filter(print, ...)` blocks from real PRISM 4.x output. PRISM
    prints ONLY non-zero values, one per line, formatted as:
        <result_position>:(<state_value>)=<value>
    e.g. "2:(3)=0.259770" means: model variable s=3 has value 0.259770.
    The number BEFORE the colon is just a result-list position, NOT the
    state index -- the real state index is the number INSIDE the parens.
    A block can also read "(all zero)" if every state is 0, and values can
    be the literal word "Infinity".

    Returns: list (per property) of lists (per state, indexed 0..num_states-1)
    of floats, defaulting to 0.0 for any state not explicitly listed (PRISM
    only prints non-zero entries), or None if the block couldn't be parsed
    at all (format totally unrecognised -- surfaces as NO PARSE downstream).
    """
    blocks = re.split(r"Model checking:", raw)[1:]  # drop preamble
    line_re = re.compile(
        r"^\s*\d+\s*:\s*\((\d+)\)\s*=\s*(Infinity|[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\s*$",
        re.MULTILINE,
    )
    all_results = []
    for block in blocks[:num_props]:
        if "Results (non-zero only)" not in block and "Results (including" not in block:
            all_results.append(None)  # couldn't even find a results section
            continue

        per_state = [0.0] * num_states  # unlisted => implicitly zero
        if "(all zero)" in block:
            all_results.append(per_state)
            continue

        matches = list(line_re.finditer(block))
        for m in matches:
            idx = int(m.group(1))
            val_str = m.group(2)
            val = float("inf") if val_str == "Infinity" else float(val_str)
            if 0 <= idx < num_states:
                per_state[idx] = val
        all_results.append(per_state if matches else None)
    return all_results


# ── Step 5: compare + report ────────────────────────────────────────────────
def compare(amc, prism_raw: str, tolerance: float):
    ts, abss = amc.transient_states, amc.absorbing_states
    t, a = len(ts), len(abss)
    num_props = a + 1  # one P=? per absorbing state, plus one global R{"steps"}
    num_states = t + a

    parsed = parse_prism_filter_output(prism_raw, num_props, num_states)
    prob_blocks = parsed[:a]
    steps_block = parsed[a] if len(parsed) > a else None

    print("\n" + "=" * 90)
    print("NETVA vs PRISM -- cross-validation report")
    print("=" * 90)

    all_pass = True
    name_w = max(20, max((len(s) for s in ts), default=20) + 2)

    # -- Part 1: absorption probabilities, one table per target (matches B) --
    for j, target in enumerate(abss):
        prob_vals = prob_blocks[j]
        print(f"\n--- Absorption probability into: {target} ---")
        print(f"{'state':<{name_w}}{'NETVA P(absorb)':<18}{'PRISM P(absorb)':<18}{'diff':<12}{'status'}")

        for i, s in enumerate(ts):
            netva_p = amc.B[i, j]
            prism_p = prob_vals[i] if prob_vals is not None else None

            if prism_p is None:
                status, all_pass = "NO PARSE", False
                diff_str, prism_str = "n/a", "?"
            else:
                diff = abs(netva_p - prism_p)
                ok = diff <= tolerance
                status = "PASS" if ok else "FAIL"
                all_pass = all_pass and ok
                diff_str, prism_str = f"{diff:.6f}", f"{prism_p:.4f}"

            print(f"{s:<{name_w}}{netva_p:<18.4f}{prism_str:<18}{diff_str:<12}{status}")

    # -- Part 2: expected steps to ANY absorption (matches t_vec, one table) --
    print(f"\n--- Expected steps to absorption (into ANY target) ---")
    print(f"{'state':<{name_w}}{'NETVA E[steps]':<18}{'PRISM E[steps]':<18}{'diff':<12}{'status'}")
    for i, s in enumerate(ts):
        netva_t = amc.t_vec[i]
        prism_t = steps_block[i] if steps_block is not None else None

        if prism_t is None:
            status, all_pass = "NO PARSE", False
            diff_str, prism_str = "n/a", "?"
        elif prism_t == float("inf"):
            # Shouldn't happen for the "any_absorbing" label (absorption is
            # certain), but guard against it rather than crash on the diff.
            status, all_pass = "FAIL (inf)", False
            diff_str, prism_str = "n/a", "Infinity"
        else:
            diff = abs(netva_t - prism_t)
            ok = diff <= tolerance
            status = "PASS" if ok else "FAIL"
            all_pass = all_pass and ok
            diff_str, prism_str = f"{diff:.6f}", f"{prism_t:.4f}"

        print(f"{s:<{name_w}}{netva_t:<18.4f}{prism_str:<18}{diff_str:<12}{status}")

    print("\n" + "=" * 90)
    if all_pass:
        print(f"OVERALL: PASS -- all values agree within tolerance ({tolerance}).")
    else:
        print("OVERALL: FAIL or UNPARSED -- see table above.")
        print(f"Raw PRISM output saved to: {PRISM_LOG}")
        print("If rows show 'NO PARSE', your PRISM version's output format differs")
        print("slightly from what this script expects -- open the raw log above,")
        print("find the numbers by eye, and adjust parse_prism_filter_output()'s regex.")
    print("=" * 90)
    return all_pass


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tolerance", type=float, default=1e-3,
                         help="Max allowed absolute difference (default 0.001)")
    args = parser.parse_args()

    print("[1/4] Running NETVA's AMC pipeline...")
    amc = run_netva_amc()
    print(f"      -> {len(amc.transient_states)} transient states, "
          f"{len(amc.absorbing_states)} absorbing states, "
          f"solver={amc.solver_method}, converged={amc.solver_converged}")
    self_check_netva(amc)

    print("[2/4] Writing PRISM model + properties from live matrices...")
    write_prism_files(amc)
    print(f"      -> {PM_FILE}\n      -> {PCTL_FILE}")

    print("[3/4] Running PRISM...")
    raw = run_prism()
    print(f"      -> raw output saved to {PRISM_LOG}")

    print("[4/4] Comparing results...")
    passed = compare(amc, raw, args.tolerance)

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()