"""Firewall / ACL rule parser — iptables-save + AWS SG JSON + lab generator."""
from __future__ import annotations

import json
import re

from backend.ingestion.models import RawACLRule, RawACLConfig


def parse_acl(data: str | dict) -> RawACLConfig:
    """Parse firewall rules from iptables-save text or AWS SG JSON."""
    if isinstance(data, dict):
        return _parse_aws_sg(data)
    if isinstance(data, str):
        try:
            parsed = json.loads(data)
            if isinstance(parsed, dict):
                return _parse_aws_sg(parsed)
        except (json.JSONDecodeError, ValueError):
            pass
        return _parse_iptables(data)
    return RawACLConfig()


def _parse_iptables(text: str) -> RawACLConfig:
    """Parse iptables-save output format."""
    rules: list[RawACLRule] = []
    default_policy = "ACCEPT"

    for line in text.strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        # Default policy line: :FORWARD ACCEPT [0:0] or :FORWARD DROP [0:0]
        policy_match = re.match(r"^:(\w+)\s+(ACCEPT|DROP|REJECT)", line)
        if policy_match:
            chain = policy_match.group(1)
            policy = policy_match.group(2)
            if chain == "FORWARD":
                default_policy = policy
            continue

        # Rule lines: -A FORWARD -s 10.10.0.0/24 -d 10.20.0.0/24 -j DROP
        rule_match = re.match(r"^-[AI]\s+(\w+)\s+(.*)$", line)
        if not rule_match:
            continue

        chain = rule_match.group(1)
        rest = rule_match.group(2)

        # Skip conntrack / log / masquerade rules — not relevant for edge inference
        if "--ctstate" in rest or "LOG" in rest.upper() or "MASQUERADE" in rest.upper():
            continue

        src = _extract_flag(rest, "-s", "0.0.0.0/0")
        dst = _extract_flag(rest, "-d", "0.0.0.0/0")
        proto = _extract_flag(rest, "-p", "all")
        port_str = _extract_flag(rest, "--dport", None)
        port = int(port_str) if port_str and port_str.isdigit() else None
        action = _extract_flag(rest, "-j", "ACCEPT")
        comment = _extract_flag(rest, "--comment", "")

        rules.append(RawACLRule(
            chain=chain,
            action=action,
            protocol=proto,
            src=src,
            dst=dst,
            port=port,
            direction="forward" if chain == "FORWARD" else "in" if chain == "INPUT" else "out",
            comment=comment,
        ))

    return RawACLConfig(rules=rules, default_policy=default_policy)


def _extract_flag(text: str, flag: str, default: str | None) -> str | None:
    """Extract a flag value from iptables rule string."""
    pattern = re.escape(flag) + r"\s+(\S+)"
    m = re.search(pattern, text)
    return m.group(1) if m else default


def _parse_aws_sg(data: dict) -> RawACLConfig:
    """Parse AWS Security Group JSON format."""
    rules: list[RawACLRule] = []
    default_policy = "DROP"  # AWS SGs default deny

    for perm in data.get("IpPermissions", []):
        proto = perm.get("IpProtocol", "all")
        from_port = perm.get("FromPort")
        for ip_range in perm.get("IpRanges", []):
            cidr = ip_range.get("CidrIp", "0.0.0.0/0")
            rules.append(RawACLRule(
                chain="INPUT",
                action="ACCEPT",
                protocol=proto if proto != "-1" else "all",
                src=cidr,
                dst="0.0.0.0/0",
                port=from_port,
                direction="in",
                comment=ip_range.get("Description", ""),
            ))

    return RawACLConfig(rules=rules, default_policy=default_policy)


def generate_lab_acl() -> str:
    """Generate the strict iptables rules for the lab firewall.

    This output mirrors lab/firewall-rules/default.sh — default DROP between
    zones with one specific cross-zone allow rule (appserver -> database:3306).
    """
    return """# Generated by iptables-save — strict zone segmentation
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

# Intra-zone traffic — same-subnet hosts can communicate freely
-A FORWARD -s 10.10.0.0/24 -d 10.10.0.0/24 -j ACCEPT
-A FORWARD -s 10.20.0.0/24 -d 10.20.0.0/24 -j ACCEPT
-A FORWARD -s 10.30.0.0/24 -d 10.30.0.0/24 -j ACCEPT

# Cross-zone — only allowed business path: appserver -> database on MySQL port
-A FORWARD -s 10.10.0.20 -d 10.20.0.20 -p tcp --dport 3306 -j ACCEPT

# Allow SSH for management (in real deployments this would come from a bastion subnet)
-A INPUT -p tcp --dport 22 -j ACCEPT

COMMIT
"""